#%RAML 1.0 Trait

      queryParameters:
        includeFilteredBy:
          description: Whether to include filter information in the response
          type: boolean
          default: false
          required: false
