#%RAML 1.0
title: Filters for Finc Select
version: v1
baseUri: http://localhost/mod-finc-config

documentation:
  - title: mod-finc-config API
    content: This documents the API calls that can be made to query and manage filters of metadata collections

types:
  fincSelectFilter: !include schemas/fincSelectFilter.json
  fincSelectFilters: !include schemas/fincSelectFilters.json
  fincSelectFilterToCollections: !include schemas/fincSelectFilterToCollections.json
  errors: !include ./raml-util/schemas/errors.schema

traits:
  orderable: !include ./raml-util/traits/orderable.raml
  pageable: !include ./raml-util/traits/pageable.raml
  searchable: !include ./raml-util/traits/searchable.raml
  language: !include ./raml-util/traits/language.raml
  validate: !include ./raml-util/traits/validation.raml

resourceTypes:
  collection: !include ./raml-util/rtypes/collection.raml
  collection-item: !include ./raml-util/rtypes/item-collection.raml

/finc-select/filters:
  displayName: Finc select filters
  type:
    collection:
      exampleCollection: !include examples/fincSelectFilter_collection.sample
      exampleItem: !include examples/fincSelectFilter1.sample
      schemaCollection: fincSelectFilters
      schemaItem: fincSelectFilter
  get:
    is: [
      searchable: {description: "", example: "active=true sortBy username"},
      orderable: {fieldsList: "field A, field B"},
      pageable
    ]
    description: Get all filters
  post:
    is: [validate]
    description: Post new finc select filter
  /{id}:
    type:
      collection-item:
        exampleItem: !include examples/fincSelectFilter1.sample
        schema: fincSelectFilter
    get:
      description: Get one finc select filter identified by id
    delete:
      description: Delete a filter identified by id
    put:
      description: Put a filter identified by id
    /collections:
      get:
        description: Get collections the current filter is assigned to
        responses:
          200:
            description: The collection IDs of collection assigned to this filter
            body:
              application/json:
                type: fincSelectFilterToCollections
                example: !include examples/fincSelectFilterToMetadataCollections.sample
          404:
            description: Not found
            body:
              text/plain:
                example: Not found
          500:
            description: Internal server error
            body:
              text/plain:
                example: "Internal server error"
      put:
        description: Add collections to this filter
        body:
          application/json:
            type: fincSelectFilterToCollections
        responses:
          200:
            description: The added collections
            body:
              application/json:
                type: fincSelectFilterToCollections
                example: !include examples/fincSelectFilterToMetadataCollections.sample
          400:
            description: Bad request
            body:
              text/plain:
                example: Bad request
          500:
            description: Internal server error
            body:
              text/plain:
                example: Internal server error
