#%RAML 1.0
title: Finc Config EZB Credentials
version: v1
baseUri: http://github.com/org/folio/mod-finc-config

documentation:
  - title: mod-finc-config EZB Credentials API
    content: This documents the API calls that can be made to query and manage EZB credentials of the system

types:
  credential: !include schemas/ezbCredential.json
  credentials: !include schemas/ezbCredentials.json
  errors: !include raml-util/schemas/errors.schema

traits:
  pageable: !include raml-util/traits/pageable.raml
  searchable: !include raml-util/traits/searchable.raml
  language: !include raml-util/traits/language.raml
  validate: !include raml-util/traits/validation.raml

resourceTypes:
  collection: !include raml-util/rtypes/collection.raml
  collection-item: !include raml-util/rtypes/item-collection.raml

/finc-config/ezb-credentials:
  type:
    collection:
      exampleCollection: !include examples/fincConfigEZBCredentialCollection.sample
      exampleItem: !include examples/fincConfigEZBCredential.sample
      schemaCollection: credentials
      schemaItem: credential
  get:
    is: [
      searchable: {description: "", example: ""},
      pageable
    ]
    description: Return a list of isisls
  post:
    is: [validate]
    description: Create an isil
  /{isil}:
    type:
      collection-item:
        exampleItem: !include examples/fincConfigEZBCredential.sample
        schema: credential
    get:
      description: Get one ezb credentials entry by isil
    delete:
      description: Delete an ezb credentials entry identified by isil
    put:
      description: Put an ezb credentials entry identified by isil