#%RAML 1.0
title: Finc Config EZB Credentials
version: v1
baseUri: http://github.com/org/folio/mod-finc-config

documentation:
  - title: mod-finc-config EZB Credentials API
    content: This documents the API calls that can be made to query and manage EZB credentials of the system

types:
  credential: !include schemas/ezbCredential.json
  credentials: !include schemas/ezbCredentials.json
  errors: !include raml-util/schemas/errors.schema

traits:
  pageable: !include raml-util/traits/pageable.raml
  searchable: !include raml-util/traits/searchable.raml
  language: !include raml-util/traits/language.raml
  validate: !include raml-util/traits/validation.raml

resourceTypes:
  collection: !include raml-util/rtypes/collection.raml
  collection-item: !include raml-util/rtypes/item-collection.raml

/finc-select/ezb-credentials:
  get:
    description: Get ezb credential entry
    responses:
      200:
        description: The tenant's ezb credential entry
        body:
          application/json:
            type: credential
            example: !include examples/fincConfigEZBCredential.sample
      404:
        description: Not found
        body:
          text/plain:
            example: Not found
      500:
        description: Internal server error
        body:
          text/plain:
            example: "Internal server error"
  put:
    description: Add or edit an ezb credential entry
    body:
      application/json:
        type: credential
    responses:
      200:
        description: The added collections
        body:
          application/json:
            type: credential
            example: !include examples/fincConfigEZBCredential.sample
      400:
        description: Bad request
        body:
          text/plain:
            example: Bad request
      500:
        description: Internal server error
        body:
          text/plain:
            example: Internal server error
  delete:
    description: Delete ezb credential
    responses:
      204:
        description: "Delete succeeded"
      400:
        description: "Bad request"
        body:
          text/plain:
      500:
        description: "Internal server error"
        body:
          text/plain:
            example: "Internal server error, contact administrator"