#%RAML 1.0
title: Files for Finc Config
version: v1
baseUri: http://localhost/mod-finc-config

documentation:
  - title: mod-finc-config API
    content: This documents the API calls that can be made to query files

traits:
  orderable: !include ./raml-util/traits/orderable.raml
  pageable: !include ./raml-util/traits/pageable.raml
  searchable: !include ./raml-util/traits/searchable.raml
  language: !include ./raml-util/traits/language.raml

resourceTypes:
  collection-item: !include ./raml-util/rtypes/item-collection.raml

/finc-config/files:
  displayName: Finc config files
  post:
    queryParameters:
      isil:
        type: string
        required: true
        description: The isil this file is assigned to.
    description: Upload/update a finc select file.
    body:
      application/octet-stream:
    responses:
      200:
        description: Uploading the file was successful. Returns uuid of uploaded file. This uuid will be referenced in 'fincSelectFilterFile' as value of the property 'file'.
        body:
          text/plain:
      400:
        body:
          text/plain:
      500:
        body:
          text/plain:
  /{id}:
    get:
      description: Get file by id
      responses:
        200:
          body:
            application/octet-stream:
        404:
          body:
            text/plain:
        500:
          description: Server Error
          body:
            text/plain:
    delete:
      description: Delete a file identified by id
      responses:
        204:
          description: "Delete succeeded"
        400:
          description: "Bad request"
          body:
            text/plain:
        500:
          description: "Internal server error"
          body:
            text/plain:
              example: "Internal server error, contact administrator"