#%RAML 1.0
title: Metadata Collections Select
version: v1
baseUri: http://localhost/mod-finc-config

documentation:
  - title: mod-finc-config API
    content: This documents the API calls that can be made to query and manage metadata sources for the current tenant/isil

types:
  fincSelectMetadataSource: !include schemas/fincSelectMetadataSource.json
  fincSelectMetadataSources: !include schemas/fincSelectMetadataSources.json
  fincSelectMetadataCollection: !include schemas/fincSelectMetadataCollection.json
  fincSelectMetadataCollections: !include schemas/fincSelectMetadataCollections.json
  select: !include schemas/select.json
  errors: !include ./raml-util/schemas/errors.schema

traits:
  orderable: !include ./raml-util/traits/orderable.raml
  pageable: !include ./raml-util/traits/pageable.raml
  searchable: !include ./raml-util/traits/searchable.raml
  language: !include ./raml-util/traits/language.raml
  validate: !include ./raml-util/traits/validation.raml

resourceTypes:
  collection: !include ./raml-util/rtypes/collection.raml
  collection-item: !include ./raml-util/rtypes/item-collection.raml

/finc-select/metadata-sources:
  displayName: Metadata Sources Select
  type:
    collection:
      exampleCollection: !include examples/fincSelectMetadataSource_collection.sample
      exampleItem: !include examples/fincSelectMetadataSource.sample
      schemaCollection: fincSelectMetadataSources
      schemaItem: fincSelectMetadataSource
  get:
    is: [
      searchable: {description: "", example: "((label=\"Journals*\") and status=(\"active\" or \"technical implementation\") and selected=\"none\") sortby label"},
      orderable: {fieldsList: "label, sourceId, status, lastProcessed"},
      pageable
    ]
    description: Get all metadata sources
  /{id}:
    type:
      collection-item:
        exampleItem: !include examples/fincSelectMetadataSource.sample
        schema: fincSelectMetadataSource
    get:
      description: Get one metadata source identified by id
    /collections:
      get:
        description: Get metadata collections assigned to this metadata source
      /select-all:
        type:
          collection-item:
            exampleItem: !include examples/select.sample
            schema: select
        put:
          description: Put, if all metadata collections of this source are selected resp. deselected


