#%RAML 1.0
title: Files for Finc Config
version: v1
baseUri: http://localhost/mod-finc-config

documentation:
  - title: mod-finc-config API
    content: This documents the API calls that can be made to query files

traits:
  orderable: !include ./raml-util/traits/orderable.raml
  pageable: !include ./raml-util/traits/pageable.raml
  searchable: !include ./raml-util/traits/searchable.raml
  language: !include ./raml-util/traits/language.raml

resourceTypes:
  collection-item: !include ./raml-util/rtypes/item-collection.raml

/finc-config/files:
  displayName: Finc config files
  /{id}:
    get:
      description: Get file by id
      responses:
        200:
          body:
            application/octet-stream:
        404:
          body:
            text/plain:
        500:
          description: Server Error
          body:
            text/plain: